### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dallinbeutler** [EcsRx/ecsrx#1]
Link for " bare bones required setup" is broken on the main readme page under Quick Start

**Comment by grofit** [comment]
Hey,

Sorry buddy its mainly down to this part of the library being in constant change due to ongoing discord with rx.net and unirx, I (and the rest of the rx community) is starting to agree on some of these things now so hopefully a single version will be finalized here soon and some of the docs and examples will be a bit more static.

The main reason that the link is broken now is because I have moved some of the unity specific stuff down into the View/Infrastructure namespaces within this shared core so the old example was no longer applicable now that there is an `EcsRxApplication` notion rather than you having to roll your own like was in the first version.

Anyway I will update the link, thanks for letting me know.

**Comment by grofit** [comment]
Updated readme some more, one thing to mention if you are actually wanting to use this lib, it is still missing a "drop in and go" style module, as the quickest route to get up and go is to implement an `EcsRxApplication` class of your own, but that requires you to have a DI wrapper which is the tricky bit.

The example folder comes with a simple implementation which also has a Ninject DI wrapper, so if you want to use Ninject you can just lift that code and off you go. If however you do not want to use the `infrastructure` module which tries to provide some scaffolding for good design patterns etc then you would need to basically bootstrap the app manually which can be found here (where the link originally led):

https://github.com/EcsRx/ecsrx/blob/9e2c091523b2986ec12163e40da5b4c098e13fa0/src/EcsRx.Examples/Application/EcsRxApplication.cs

**Comment by grofit** [comment]
Also added a document specifically on this point:

https://github.com/EcsRx/ecsrx/blob/master/docs/setup.md

**Comment by dallinbeutler** [comment]
Awesome! This may be above my skill level, but I really do want to learn Reactive in a fun way. I'll definitely give it a shot!
